### ISSUE TITLE
Expected String, got undefined

### ISSUE THREAD

**Issue by phaalonso** [bbbco/insomnia-plugin-faker#4]
![image](https://user-images.githubusercontent.com/26033899/85859557-bef4a100-b793-11ea-8920-d8a26684c46b.png)

How I can fix this?

**Comment by bbbco** [comment]
Hey @phaalonso , can you post what your Faker value config looks like?

**Comment by phaalonso** [comment]
I don't have any config, just installed faker and is giving me this errors.

**Comment by bbbco** [comment]
Well it looks like you created a Faker object in your request body. Can you show me what that looks like?

**Comment by phaalonso** [comment]
Sure, my request body is something like this. 
```json
{
	"title": "Como lavar as mãos",
	"text": "Nessa época de pandemia, é extremamente necessário lavar as mãos!",
	"abstract": "Nessa época de pandemia, é extremamente necessário lavar as mãos!",
	"tags": [
		{
			"id": "Dengue"
		},
		{
			"id": "Covid"
		}
	]
}
```
When I tried to use in the body it was send the {% faker ... %} to the backend.

**Comment by bbbco** [comment]
Thanks. I'll have to look into this. I know insomnia has had some recent updates that I have not kept up with, so it may be that an update to the plug-in is in order.

**Comment by phaalonso** [comment]
Ok, I will be awaiting.

**Comment by gschier** [comment]
FYI, I left a comment over on https://github.com/Kong/insomnia/issues/2567 with a solution to this.

https://github.com/Kong/insomnia/issues/2567#issuecomment-683207856

**Comment by bbbco** [comment]
Closing out issue as this was fixed almost two years ago! :D
